version: '3'
services:

  mysql:
    image: mysql:8.4
    container_name: mysql
    ports:
      - "3306:3306" # 映射主機的 3306 端口到容器的 3306 端口
    environment:
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: site_learning_libray
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    platform: linux/amd64
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
    networks:
      - frontend
      - backend

volumes:
  mysql_data:


networks:
  backend:
    driver: bridge
